//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentsApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserPaymentsDBEntities : DbContext
    {
        public UserPaymentsDBEntities()
            : base("name=UserPaymentsDBEntities")
        {
        }

        private static UserPaymentsDBEntities context;
        public static UserPaymentsDBEntities GetContext()
        {
            if (context == null)
                context = new UserPaymentsDBEntities();
            return context;
        }

        public static int CurrentUserID { get; set; }
        public static void GetCurrentUserId(int id)
        {
            CurrentUserID = id;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<PaymentType> PaymentType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
