//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentsApp
{
    using System;
    using System.Collections.Generic;

    public partial class Payment
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string PaymentName { get; set; }
        public int PaymentTypeID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int Count { get; set; }
        public decimal Price { get; set; }
        public bool IsPayed { get; set; }

        public string Summ => (Price * Count).ToString("N2");
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual User User { get; set; }
    }
}
